config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  scope "/admin" do
    post "add-org-admin" => "admins#add_org_admin", as: :add_org_admin
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" }

  root "pages#landing"
  
  get "how-it-works" => "pages#how_it_works", as: :how_it_works
  get "about" => "pages#about", as: :about
  get "faq" => "pages#faq", as: :faq
  get "terms" => "pages#terms", as: :terms
  get "privacy" => "pages#privacy", as: :privacy

  get "create-campaign" => "campaigns#new", as: :new_campaign
  get "edit-campaign/:id" => "campaigns#edit", as: :edit_campaign
  resources :campaigns do
    get :autocomplete_organization_name, :on => :collection
  end
  resources :campaigns, :only => [:index, :show, :create, :update, :destroy]

  get ":campaign_id/donate" => "donations#new", as: :new_donation
  resources :donations, :only => [:create, :destroy]
  post "/donations/add-donation-message" => "donations#add_donation_message", as: :add_donation_message

  resources :journal_entries, :except => [:index, :show]

  post "create-or-update-credit-card" => "users#create_or_update_credit_card", as: :create_or_update_credit_card
  delete "delete-credit-card" => "users#delete_credit_card", as: :delete_credit_card
  resources :users, :only => [:show]

  post "follow/:user_id" => "users#follow", as: :follow
  delete "follow/:user_id" => "users#unfollow", as: :unfollow

  get "charity-admin" => "admins#index", as: :charity_admin
  post "admin/verify/:journal_entry_id" => "admins#verify", as: :verify_journal_entry
  post "admin/verify-all/:org_id" => "admins#verify_all", as: :verify_all_journal_entries_for_org
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  devise :omniauthable, :omniauth_providers => [:facebook]
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :campaigns
  has_many :donations
  has_many :journal_entries
  has_many :organizations, :through => :campaigns

  has_many :org_admins, class_name: "OrgAdmin", foreign_key: "user_id", dependent: :destroy
  has_many :organizations_as_admin, through: :org_admins, source: :organization
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  s3_credentials_hash = {
    :access_key_id => ENV['AWS_ACCESS_KEY'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }

  has_attached_file :avatar, 
                    :styles => { :small => "40x40#", :large => "200x200#" },
                    :s3_credentials => s3_credentials_hash,
                    :bucket => ENV['AWS_BUCKET'],
                    :default_url => "https://s3-us-west-2.amazonaws.com/raisechange/general/no_profile.png",
                    :s3_protocol => :https

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      # user.image = auth.info.image # assuming the user model has an image
      user.skip_confirmation!
    end
  end

  def to_param
    "#{id}-#{first_name.parameterize.downcase}-#{last_name.parameterize.downcase}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def create_or_update_stripe_customer(token)
    stripe_setup

    begin
      if self.stripe_id
        customer = retrieve_customer
        customer.card = token
        customer.save
      else
        response = Stripe::Customer.create(
          :description => self.email,
          :card => token
        )
        self.update_attributes(:stripe_id => response.id)
      end
      return {:success => true}
    rescue => e
      handle_stripe_error(e)
    end
  end

  def has_credit_cards?
    return false unless self.stripe_id
    self.credit_cards.any?
  end

  def credit_cards
    stripe_setup
    return retrieve_customer.cards.all()
  end

  def delete_credit_card
    stripe_setup
    customer = retrieve_customer
    card_id = customer.cards.data[0].id
    last4 = customer.cards.data[0].last4
    customer.cards.retrieve(card_id).delete
    return last4
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def newsfeed
    ids = []
    activities = []

    ids << self.ids_for_users_supported
    ids << self.following.map {|u| u.id}
    ids << self.id # So users can always see their own activity
    ids = ids.flatten.uniq

    activities << JournalEntry.where(:user_id => ids)
    activities << Donation.where(:user_id => ids)
    return activities.flatten.sort_by {|activity| activity.created_at}.reverse
  end

  def ids_for_users_supported
    self.donations.pluck(:user_id).uniq
  end

  def users_supported
    self.donations.map{|donation| donation.user}.uniq
  end

  private

  def stripe_setup
    Stripe.api_key = Rails.env.production? ? ENV["STRIPE_LIVE_SECRET_KEY"] : ENV["STRIPE_TEST_SECRET_KEY"]
  end

  def retrieve_customer
    Stripe::Customer.retrieve(self.stripe_id)
  end

  def handle_stripe_error(e)
    body = e.json_body
    err  = body[:error]
    return {:success => false, :message => err[:message]}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      flash[:alert] = @user.errors.full_messages.join(". ") + "."
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => :create_or_update_credit_card

  def show
    @user = User.find(params[:id])
    @user_campaigns = @user.campaigns
    @journal_entries = @user.journal_entries
    @donations = @user.donations
    @own_page = @user == current_user
    @title = "#{@user.first_name} <span class='highlight'>#{@user.last_name}</span>"
    @image = "https://s3-us-west-2.amazonaws.com/raisechange/general/generic_shovel.jpg"
    @user_profile_image = true
  end

  def create_or_update_credit_card
    status = current_user.create_or_update_stripe_customer(params[:stripeToken])
    if status[:success]
      flash[:notice] = "Your have successfully added a credit card."
    else
      flash[:alert] = status[:message]
    end
    redirect_to(:back)
  end

  def delete_credit_card
    last4 = current_user.delete_credit_card
    flash[:notice] = "Your credit card ending in #{last4} has been deleted."
    redirect_to edit_user_registration_path
  end

  def follow
    respond_to do |format|
      other_user = User.find(params[:user_id])
      current_user.follow(other_user)
      format.json { render :json => { :status => 200 } }
    end
  end

  def unfollow
    respond_to do |format|
      other_user = User.find(params[:user_id])
      current_user.unfollow(other_user)
      format.json { render :json => { :status => 200 } }
    end
  end
end

app/views/users/_big_user_picture_and_name.html.slim
= link_to profile_picture(user), user_path(user)
.campaign-show-user-name
  a href="#{user_path(user)}"
    h3
      = user.first_name
    p
      = user.last_name

app/views/users/_credit_card_form.html.slim
.row
  .col-xs-12.col-sm-6
    form#payment-form action="#{create_or_update_credit_card_path}" method="POST"
      .payment-form
        .row
          .col-xs-12
            .form-group
              label
                | * Card Number
              input.form-control.stripe-card-number data-stripe="number" type="tel" autocomplete="cc-number" placeholder="•••• •••• •••• ••••"
              span.payment-errors-number.stripe-card-error

        .row
          .col-xs-7
            .form-group
              label
                | * Expiration
              input.form-control.stripe-expiry type="tel" placeholder="MM / YYYY" ng-model="expiryDate" ng-keyup="splitDate()"
              input.form-control.stripe-exp-month.hidden data-stripe="exp-month" type="tel" placeholder="MM" value="{{month}}"
              input.form-control.stripe-exp-year.hidden data-stripe="exp-year" type="tel" placeholder="YYYY" value="{{year}}"
              span.payment-errors-exp_month.stripe-card-error
              span.payment-errors-exp_year.stripe-card-error

          .col-xs-5
            .form-group
              label
                | * CVC

              input.form-control.stripe-cvc data-stripe="cvc" size="4" type="tel" style="width: 60px;" autocomplete="off" placeholder="•••"
              span.payment-errors-cvc.stripe-card-error

  - if show_card_description
    .col-xs-12.col-sm-6
      .donation-field-description
        = "Your credit card will not be charged immediately. Every #{donation_period_name}, we will assess how many hours were logged and charge at that time. You will receive an email when your card is charged."

app/views/users/_existing_credit_cards.html.slim
.row
  .col-xs-12.col-sm-6
    label
      | Using saved card
    .list-existing-credit-cards
      - cards.data.each do |card|
        div
          = "#{card.brand}, ending in: #{card.last4}"
        div
          = "Expires: #{card.exp_month.to_s.rjust(2, '0')} / #{card.exp_year}"

  - if show_card_description
    .col-xs-12.col-sm-6
      .donation-field-description
        = "To update your credit card, please go to #{link_to 'Account settings', edit_user_registration_path}".html_safe

app/views/users/_follow_section.html.slim
.follow-section-holder ng-controller="FollowCtrl" data-following="#{current_user.following?(user)}"
  .btn.btn-default.follow-button class="#{'campaign-page' unless location == 'banner'}" data-follow-url="#{follow_path(user)}" ng-click="follow()" ng-show="!following"
    i.fa.fa-star-o
    | Follow

  .btn.unfollow-button ng-class="hovering ? 'hovering' : ''" ng-mouseover="hovering = true" ng-mouseleave="hovering = false" ng-show="following" ng-click="unfollow()" data-unfollow-url="#{unfollow_path(user)}" class="#{'campaign-page' unless location == 'banner'}"
    div ng-show="!hovering"
      i.fa.fa-star
      | Following

    div ng-show="hovering" data-unfollow-url="#{unfollow_path(user)}"
      | Unfollow

  - if location == 'campaign_page'
    .campaign-page-question-tooltip
      i.fa.fa-question-circle data-toggle="tooltip" data-placement="bottom" title="Follow to see activities by #{user.first_name} in your feed"
  - else
    i.fa.fa-question-circle data-toggle="tooltip" data-placement="right" title="Follow to see activities by #{user.first_name} in your feed"

app/views/users/_user_sign_up.html.slim
.user-sign-up-partial
  .row
    .col-xs-12.col-sm-6
      label
        | * First name
      input.form-control.account-details-input.first-name name="first_name" type="text"
      .user-sign-up-error.hide
        | Please fill in

    .col-xs-12.col-sm-6
      .donation-field-description
        | To match your credit card

  .row
    .col-xs-12.col-sm-6
      label
        | * Last name
      input.form-control.account-details-input.last-name name="last_name" type="text"
      .user-sign-up-error.hide
        | Please fill in

    .col-xs-12.col-sm-6
      .donation-field-description
        | To match your credit card (and to address you politely)

  .row
    .col-xs-12.col-sm-6
      label
        | * Email
      input.form-control.account-details-input.email-input name="email" type="email"
      .user-sign-up-error.hide
        | Please fill in correctly

    .col-xs-12.col-sm-6
      .donation-field-description
        | To send you a receipt

  .row
    .col-xs-12.col-sm-6
      label
        | * Password (min 8 characters)
      input.form-control.account-details-input.password-input name="password" type="password"
      .user-sign-up-error.hide
        | Please fill in correctly

    .col-xs-12.col-sm-6
      .donation-field-description
        = "So you can log in to track your donations and view updates from #{campaign.user.first_name}"

app/views/users/show.html.slim
.user-dashboard
  / .row
  /   .col-xs-6.col-xs-offset-3.col-sm-2.col-sm-offset-5
  /     = render "users/big_user_picture_and_name", :user => @user
  .row
    .col-xs-12.col-sm-4
      .info-box-holder.yellow
        .info-box-holder-header
          | Activities
        .info-box-holder-content
          - if @journal_entries.any?
            - @journal_entries.each do |je|
              = render "journal_entries/journal_entry_grid", :je => je, :show_campaign_title => true

          - else
            .prompt-content-holder
              - if @user_campaigns.any? && @own_page
                p
                  | Start logging them volunteer hours :)

                br
                a.call-to-action href="#{new_journal_entry_path}"
                  | Log hours
                  .arrow-right

              - elsif @own_page
                p
                  | Can't start logging activities until you start a campaign!

                br
                a.call-to-action href="#{new_campaign_path}"
                  | Create campaign
                  .arrow-right

              - else
                p
                  = "#{@user.first_name} has not logged any activities yet.".html_safe

      br

    .col-xs-12.col-sm-4
      .info-box-holder.green
        .info-box-holder-header
          | Campaigns Created
        .info-box-holder-content
          - if @user_campaigns.any?
            - @user_campaigns.each do |campaign|
              = render "campaigns/grid", :campaign => campaign

          - elsif @own_page
            .prompt-content-holder
              p
                | Have a cause you care about, and are / want to start volunteering for? Let's start a campaign!

              br
              a.call-to-action href="#{new_campaign_path}"
                | Create campaign
                .arrow-right

          - else
            .prompt-content-holder
              p
                = "#{@user.first_name} has not created any campaigns yet.".html_safe

      br

    .col-xs-12.col-sm-4
      .info-box-holder.grey
        .info-box-holder-header
          | Supporting
        .info-box-holder-content
          - if @donations.any?
            .donated-to-holder ng-controller="DonatedToGridCtrl"
              - @donations.each do |donation|
                = render "donations/donated_to_grid", :donation => donation

          - elsif @own_page
            .prompt-content-holder
              p
                | Want to support other people doing great work?

              br
              a.call-to-action href="#{campaigns_path}"
                | Browse campaigns
                .arrow-right

          - else
            .prompt-content-holder
              p
                = "#{@user.first_name} has not supported any campaigns yet.".html_safe