config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  scope "/admin" do
    post "add-org-admin" => "admins#add_org_admin", as: :add_org_admin
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" }

  root "pages#landing"
  
  get "how-it-works" => "pages#how_it_works", as: :how_it_works
  get "about" => "pages#about", as: :about
  get "faq" => "pages#faq", as: :faq
  get "terms" => "pages#terms", as: :terms
  get "privacy" => "pages#privacy", as: :privacy

  get "create-campaign" => "campaigns#new", as: :new_campaign
  get "edit-campaign/:id" => "campaigns#edit", as: :edit_campaign
  resources :campaigns do
    get :autocomplete_organization_name, :on => :collection
  end
  resources :campaigns, :only => [:index, :show, :create, :update, :destroy]

  get ":campaign_id/donate" => "donations#new", as: :new_donation
  resources :donations, :only => [:create, :destroy]
  post "/donations/add-donation-message" => "donations#add_donation_message", as: :add_donation_message

  resources :journal_entries, :except => [:index, :show]

  post "create-or-update-credit-card" => "users#create_or_update_credit_card", as: :create_or_update_credit_card
  delete "delete-credit-card" => "users#delete_credit_card", as: :delete_credit_card
  resources :users, :only => [:show]

  post "follow/:user_id" => "users#follow", as: :follow
  delete "follow/:user_id" => "users#unfollow", as: :unfollow

  get "charity-admin" => "admins#index", as: :charity_admin
  post "admin/verify/:journal_entry_id" => "admins#verify", as: :verify_journal_entry
  post "admin/verify-all/:org_id" => "admins#verify_all", as: :verify_all_journal_entries_for_org
end

app/views/pages/_following_and_supporting.html.slim
.following-and-supporting-holder
  .info-box-holder.grey
    .info-box-holder-header
      | Awesome people
    .info-box-holder-content
      - if current_user.donations.any?
        .title
          | Supporting:

        p
          ul.list-inline.avatar-list
            - current_user.users_supported.each do |user|
              li data-toggle="tooltip" data-placement="bottom" title="#{user.full_name}"
                = link_to avatar(user), user_path(user)

      - if current_user.following.any?
        .title
          | Following:

        p
          ul.list-inline.avatar-list
            - current_user.following.each do |user|
              li data-toggle="tooltip" data-placement="bottom" title="#{user.full_name}"
                = link_to avatar(user), user_path(user)

      - if current_user.donations.empty? && current_user.following.empty?
        p
          | Follow or support others to see their updates in your news feed!

        p
          = link_to "Browse campaigns", campaigns_path

app/views/pages/_how_it_works.html.slim
.how-it-works-page
  .row
    .col-xs-12
      .content-holder
        h3
          | Don't ask for donations. Earn them.
        p
          | Raise Change is a platform to raise micro donations for each hour someone volunteers. 
        p
          | For example, a volunteer can start a campaign for the local food bank. If 10 friends and family support the campaign for $0.25 an hour, and the volunteer does 10 hours per month, the volunteer will raise $25 for the food bank per month.

        p
          | Volunteers can choose which nonprofit receives the funds. Supporters know in advance where the money is going. Also, supporters can set a max amount they are comfortable donating per month, in case the volunteer goes on a volunteering binge.

        p
          = "Still confused? Check out our #{link_to 'FAQ', faq_path}!".html_safe

app/views/pages/_how_it_works_modal.html.slim
#how-it-works-modal.modal.fade tabindex="-1" role="dialog"
  .modal-dialog.modal-md
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
            | &times;
        h2.modal-title
          = "How it <span class='highlight'>works</span>".html_safe

      .modal-body
        = render "pages/how_it_works"

      .modal-footer
        button.btn-lg.btn-default type="button" data-dismiss="modal"
          | Got it :)

app/views/pages/_logged_in_landing.html.slim
.container
  .row
    .col-xs-12
      .main-content
        - if @activities.any? || current_user.following.any? || current_user.donations.any?
          .row
            .col-xs-12.col-sm-3
              .info-box-holder.yellow
                .info-box-holder-header
                  | Greetings
                .info-box-holder-content
                  .news-feed-left-side-holder
                    ul.list-inline
                      li
                        = avatar(current_user)
                      li.greeting
                        = "Hi #{link_to current_user.first_name, user_path(current_user)}!".html_safe
                    p
                      | Here's how the people you support and follow have been raising change.

                    p
                      | Inspired?

                    p
                      = link_to "Create your own campaign", new_campaign_path

                    p
                      = link_to "Browse other campaigns", campaigns_path

                    p
                      = link_to "I'm feeling lucky", campaign_path(Campaign.all.sample)

                  .visible-xs
                    hr

            .col-xs-12.visible-xs
              = render "following_and_supporting"

            .col-xs-12.col-sm-6
              .info-box-holder.green
                .info-box-holder-header
                  | News feed
                .info-box-holder-content
                  - if @activities.any?
                    - @activities.each do |activity|
                      - if activity.is_a? JournalEntry
                        = render "journal_entries/journal_entry_grid", :je => activity, :show_campaign_title => true
                      - else
                        = render "donations/donation_in_newsfeed", :donation => activity

                  - else
                    | Hum dee dum... just waiting for people to post some activities.

            .col-sm-3.hidden-xs
              = render "following_and_supporting"

        - else

          .row
            .col-xs-12
              .no-news-yet-news-feed-holder
                h2
                  = "Welcome #{current_user.first_name}!"

                p.browse-paragraph
                  | This is where your news feed will show up. Start following or supporting others on the site to see their updates and activities.

                a.call-to-action href="#{campaigns_path}"
                  | Browse campaigns
                  .arrow-right

                - if current_user.campaigns.empty?
                  .clearfix

                  p.create-paragraph
                    | Or, you can also create your own campaign!

                  a.call-to-action.main href="#{new_campaign_path}"
                    | Create campaign
                    .arrow-right.main

              br

app/views/pages/_non_logged_in_landing.html.slim
.landing-main-holder
  .hidden-xs
    h1
      | Raise charitable donations
    h1
      | each hour you volunteer

  .visible-xs
    h1
      | Raise charitable donations each hour you volunteer

  .call-to-action-holder
    a.call-to-action.main href="#{new_campaign_path}"
      | Get started
      .arrow-right.main

    a.call-to-action href="" data-toggle="modal" data-target="#how-it-works-modal"
      | How it works
      .arrow-right

app/views/pages/about.html.slim
.about-page
  .row
    .col-xs-12.col-sm-12
      .text-only-holder
       | Our mission
       .vertical-divider

  .row.individual-bio
    .col-xs-12.col-sm-12
      .text-only-holder-content
        | At Raise Change, our mission is to inspire people to volunteer and help causes they care about. Our platform allows individuals to do just that by providing them the tools to create their own personal campaigns that they can share with friends, family, and the rest of the world in order to earn donations. Our research suggests that people rather donate to a cause when they are supporting someone else's volunteer work rather than simply donating a flat amount. Raise Change is the world's first platform that allows individuals to earn donations per each volunteer hour they complete.  
  .vertical-divider
  .row
    .col-xs-12.col-sm-12
      .text-only-holder
       | Who we are
      .vertical-divider

    .col-xs-12.col-sm-12
      .row.individual-bio
        .col-xs-12.col-sm-3
          .image-only-holder
            = image_tag "https://s3-us-west-2.amazonaws.com/raisechange/general/bios/sam_sullivan.jpg", :width => "100%", :height => "200px", :class => "img-thumbnail"
        .col-xs-12.col-sm-9
          .text-only-holder-title
            | Sam Sullivan
          .text-only-holder-subtitle
            | Board of Advisors
          .text-only-holder-content
            | Sam Sullivan has founded a number of initiatives to support the quality of life of people with disabilities including  assistive devices and opportunities for music, sailing, wilderness access and employment. He also founded Global Civic which supports public education, free access to archives and an aboriginal language revival project.  He has served as Mayor of Vancouver and is currently a Member of the Legislative Assembly. He has received the Order of Canada.
      .vertical-divider    

    .col-xs-12.col-sm-12
      .row.individual-bio
        .col-xs-12.col-sm-3
          .image-only-holder
            = image_tag "https://s3-us-west-2.amazonaws.com/raisechange/general/bios/Leonard_Schein_compressed.jpg", :width => "100%", :height => "200px", :class => "  img-thumbnail"
        .col-xs-12.col-sm-9
          .text-only-holder-title
            | Leonard Schein
          .text-only-holder-subtitle
            | Board of Advisors
          .text-only-holder-content
            | Leonard Schein (now retired) is the founder of the Vancouver International Film Festival and Festival Cinemas which operated the Fifth Avenue Cinemas, the Park and Ridge Theatre. He is also a retired Registered Psychologist. He is currently on the Board of Directors of Canadian Cancer Prevention Centre Foundation, Coast Mental Health Foundation, Ecojustice, and InspireHealth. He has served on many Board of Directors including the Canadian Cancer Society (Chair of the British Columbia and Yukon Division), Vancouver Economic Development Commission, BC Film, BC CHILD Foundation, Vancouver Fringe Festival, Cambie Village Business Association, Karen Jameson Dance Company, Vancouver Jewish Film Festival Society, and Alliance Atlantic Cinemas. 
          .text-only-holder-content
            | He has been awarded the Queen Elizabeth II Diamond Jubilee Medal, British Columbia Community Achievement Award, British Columbia Entertainment Hall of Fame, University of Regina Lifetime Achievement Award, Westside Business Person of the Year, and the Achievement Award for Contribution to the British Columbia Film Industry and the Canadian Picture Pioneers.
      .vertical-divider

    .col-xs-12.col-sm-12
      .row.individual-bio
        .col-xs-12.col-sm-3
          .image-only-holder
            = image_tag "https://s3-us-west-2.amazonaws.com/raisechange/general/bios/alfredo.jpg", :width => "100%", :height => "200px", :class => "img-thumbnail"
        .col-xs-12.col-sm-9
          .text-only-holder-title
            | Alfredo Di Blasio
          .text-only-holder-subtitle
            | Board of Advisors
          .text-only-holder-content
            | Alfredo serves as Invidi's Senior VP of Corporate development.  He also has experience expanding companies into International markets. Earlier in Fred's career he worked with Bell Cablemedia in London before going to work for AT&T Corp and AT&T Broadband in the Strategic Development Group. After AT&T, Fred worked for Telus in Canada for several years in different positions including VP-Consumer Product Marketing, VP-Content and finally VP-Business Solutions. Most recently Fred has been working with Shaw Communications as an Advisor working on a Big Data strategy and advising Shaw's senior management on addressable advertising. Mr. Di Blasio received M.B.A. in General Management from Queens College, Cambridge University and B.A. in International Business from European Business School.
      .vertical-divider

    .col-xs-12.col-sm-12
      .row.individual-bio
        .col-xs-12.col-sm-3
          .image-only-holder
            = image_tag "https://s3-us-west-2.amazonaws.com/raisechange/general/bios/nicopic_compressed.jpg", :width => "100%", :height => "200px", :class => "img-thumbnail"
        .col-xs-12.col-sm-9
          .text-only-holder-title
            | Dr. Nicolas Eichhorst 
          .text-only-holder-subtitle
            | Co-founder
          .text-only-holder-content
            | Dr. Eichhorst is a Primary Care Physician at Vancouver Coastal Health and a Clinical Instructor at the UBC Faculty of Medicine. Raise Change was inspired by two things he experienced. The first was that friends and collegue wanted to hear about the outreach volunteer work he used to do at Coast Mental Health, and presently as a board member for Aids Vancouver. It was more than mere curiosity for many and they were both interested and inspired to get involved, and many have. Perhaps we are all very busy, and sometimes it's just a matter of discovering that even small amounts of time volunteering can make a big difference. The story mattered, and he found that as he told the stories, it reinforced his sense of commitment to the work he was doing, and so Raise Change is a platform for the narrative. That is why one has the option to follow a campaign without sponsoring financially, so that volunteers can inspire, without pressure, to get others involved to volunteer, to inform others of the options.
          .text-only-holder-content
            | The second was that despite knowing that most social enterprise non-profits operate through charity funding, he didn't enjoy asking for donations, despite evidence showing that people actually like to give for causes they believe in. Raise Change was designed to make it about the give, not the ask. Raise Change permits one to follow or sponsor a volunteer campaign. That is also why the donation rate is fixed at 25 cents per volunteer hour, so that giving is easy, and most people can sponsor a volunteer campaign if inspired without financial strain, but because this is a crowd based funding platform, succesful campaigns can accumulate exponentially. Plus, for those who want to give more, there is a top up option available as well.
      .vertical-divider

    .col-xs-12.col-sm-12
      .row.individual-bio
        .col-xs-12.col-sm-3
          .image-only-holder
            = image_tag "https://s3-us-west-2.amazonaws.com/raisechange/general/bios/david_wen.jpg", :width => "100%", :height => "200px", :class => "img-thumbnail"
        .col-xs-12.col-sm-9
          .text-only-holder-title
            | David Wen
          .text-only-holder-subtitle
             | Co-founder
          .text-only-holder-content
            | Entrepreneurial and versatile, he's a full-stack web and app developer with a background in management consulting, finance, marketing, and various business ventures. Additionally, he founded, ran, and volunteered at various charities and not-for-profit organizations, focusing on poverty, volunteerism, and assisting marginalized people.
      .vertical-divider

app/views/pages/faq.html.slim
.row
  .col-xs-12
    .faq-holder ng-controller="FAQCtrl"
      .question-section
        .row
          - @sections.each do |section|
            .col-xs-12.col-sm-4
              h4
                b
                  = section[:name]

              - section[:questions].each_with_index do |question, i|
                p
                  a href="##{section[:id] + i.to_s}"
                    = question[:question]

      hr

      - @sections.each do |section|
        h4
          b
            = section[:name]

        - section[:questions].each_with_index do |question, i|
          .question-holder
            h5 id="#{section[:id] + i.to_s}"
              b
                = question[:question]

            .answer
              - question[:answer_paragraphs].each do |answer|
                p
                  = answer.html_safe

            a.back-to-top-link href="#wrap"
              i.fa.fa-caret-up
              | Back to top

        hr

app/views/pages/how_it_works.html.slim
= render "how_it_works"

app/views/pages/landing.html.slim
div ng-controller="LandingCtrl"
  - if user_signed_in?
    = render "logged_in_landing"
  - else
    = render "non_logged_in_landing"

app/views/pages/privacy.html.slim
.row
  .col-xs-12
    h1
      | Overview

    p
      | This privacy policy discloses the privacy practices for Raise Change (raisechange.com, raisechange.org). This privacy policy applies solely to information collected by this web site. It will notify you of the following:

    ol
      li
        | What personally identifiable information is collected from you through the web site, how it is used and with whom it may be shared.
      li
        | What choices are available to you regarding the use of your data.
      li
        | The security procedures in place to protect the misuse of your information.
      li
        | How you can correct any inaccuracies in the information.

    h3
      | Information Collection, Use, and Sharing 

    p
      | We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.

    p
      | We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request.

    p
      | Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.

    h3
      | Your Access to and Control Over Information 

    p
      | You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:

    ul
      li
        | See what data we have about you, if any.
      li
        | Change/correct any data we have about you.
      li
        | Have us delete any data we have about you.
      li
        | Express any concern you have about our use of your data.

    h3
      | Security 

    p
      | We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.

    p
      | While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.

    h3
      | Updates

    p
      | Our Privacy Policy may change from time to time and all updates will be posted on this page.

    p
      = "If you feel that we are not abiding by this privacy policy, you should contact us immediately via email at #{general_contact_email}."

    h3
      | Registration 

    p
      | In order to use certain parts of this website, a user must first complete the registration form. During registration a user is required to give certain information (name and email address). This information is used to contact you about the products/services on our site in which you have expressed interest. If you make a bid, you also need to provide your phone number so that we can contact you about receiving your reward if you win. At your option, you may also provide demographic information about yourself, but it is not required.

    h3
      | Cookies 

    p
      | We use "cookies" on this site. A cookie is a piece of data stored on a site visitor's hard drive to help us improve your access to our site and identify repeat visitors to our site. For instance, when we use a cookie to identify you, you would not have to log in a password more than once, thereby saving time while on our site. Cookies can also enable us to track and target the interests of our users to enhance the experience on our site. Usage of a cookie is in no way linked to any personally identifiable information on our site.

    p
      | Some of our business partners may use cookies on our site. However, we have no access to or control over these cookies.

    h3
      | Sharing 

    p
      | We share aggregated demographic information with our partners. This is not linked to any personal information that can identify any individual person.

    h3
      | Purchases

    p
      | We use a credit card processing company (Stripe) to bill users for goods and services. Stripe do not retain, share, store or use personally identifiable information for any secondary purposes beyond filling your order. When the user signs up for these services, we will share names, or other contact information that is necessary for the third party to provide these services. These parties are not allowed to use personally identifiable information except for the purpose of providing these services.

    h3
      | Links

    p
      | This web site contains links to other sites. Please be aware that we are not responsible for the content or privacy practices of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of any other site that collects personally identifiable information.

app/views/pages/terms.html.slim
.row
  .col-xs-12
    h3
      | Overview

    p
      | Raise Change ("Raise Change") offers this website ("raisechange.com" and "raisechange.org"), including all information, software, products and services available from this website or offered as part of or in conjunction with this website, to you, the user, conditioned upon your acceptance of all of the terms, conditions, policies and notices stated here. Raise Change reserves the right to make changes to these Terms and Conditions immediately by posting the changed Terms and Conditions in this location.

    p
      | Your continued use of this website constitutes your agreement to all such terms, conditions and notices, and any changes to the Terms and Conditions made by Raise Change.

    p
      | The term "Raise Change" or "us" or "we" refers to the owner of the website. The term "you" refers to the user or viewer of our website.

    p
      | The use of this website is subject to the following terms of use:

    p
      | Use the website at your own risk. This website is provided to you "as is," without warranty of any kind either express or implied. Neither Raise Change nor its employees, agents, third-party information providers, merchants, licensors or the like warrant that this website or its operation will be accurate, reliable, uninterrupted or error-free. No agent or representative has the authority to create any warranty regarding this website on behalf of Raise Change. Raise Change reserves the right to change or discontinue at any time any aspect or feature of this website.

    h3
      | Exclusion of Liability

    p
      | The content of the pages of this website is for your general information and use only. It is subject to change without notice.

    p
      | Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.

    h3
      | Indemnification

    p
      | You agree to release, defend, indemnify, and hold Raise Change and its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (a) your access to or use of this website; (b) your user Content; (c) your (i) interaction with any other user, (ii) donating to a campaign, or (iii) creating a campaign; (d) the use of this website, including but not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of using this website.

    p
      | This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.

    p
      | Unauthorized use of this website may give rise to a claim for damages and/or be a criminal offense.

    p
      | From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).

    h3
      | Copyright

    p
      | Except for material in the public domain under Canadian or United States copyright law, all material contained on this website (including all software, HTML code, Javascript scripts, and other code) is protected by Canadian and foreign copyright laws. Except as otherwise expressly provided in these terms and conditions, you may not copy, distribute, transmit, display, perform, reproduce, publish, license, modify, rewrite, create derivative works from, transfer, or sell any material contained on this website without the prior consent of the copyright owner.

    p
      | None of the material contained on Raise Change may be reverse-engineered, disassembled, decompiled, transcribed, stored in a retrieval system, translated into any language or computer language, retransmitted in any form or by any means (electronic, mechanical, photo reproduction, recordation or otherwise), resold or redistributed without the prior written consent of Raise Change. Violation of this provision may result in severe civil and criminal penalties.