config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  scope "/admin" do
    post "add-org-admin" => "admins#add_org_admin", as: :add_org_admin
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" }

  root "pages#landing"
  
  get "how-it-works" => "pages#how_it_works", as: :how_it_works
  get "about" => "pages#about", as: :about
  get "faq" => "pages#faq", as: :faq
  get "terms" => "pages#terms", as: :terms
  get "privacy" => "pages#privacy", as: :privacy

  get "create-campaign" => "campaigns#new", as: :new_campaign
  get "edit-campaign/:id" => "campaigns#edit", as: :edit_campaign
  resources :campaigns do
    get :autocomplete_organization_name, :on => :collection
  end
  resources :campaigns, :only => [:index, :show, :create, :update, :destroy]

  get ":campaign_id/donate" => "donations#new", as: :new_donation
  resources :donations, :only => [:create, :destroy]
  post "/donations/add-donation-message" => "donations#add_donation_message", as: :add_donation_message

  resources :journal_entries, :except => [:index, :show]

  post "create-or-update-credit-card" => "users#create_or_update_credit_card", as: :create_or_update_credit_card
  delete "delete-credit-card" => "users#delete_credit_card", as: :delete_credit_card
  resources :users, :only => [:show]

  post "follow/:user_id" => "users#follow", as: :follow
  delete "follow/:user_id" => "users#unfollow", as: :unfollow

  get "charity-admin" => "admins#index", as: :charity_admin
  post "admin/verify/:journal_entry_id" => "admins#verify", as: :verify_journal_entry
  post "admin/verify-all/:org_id" => "admins#verify_all", as: :verify_all_journal_entries_for_org
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  validates :title, :organization_name, :description, presence: true

  belongs_to :user
  belongs_to :organization
  has_many :donations, :dependent => :destroy
  has_many :journal_entries, :dependent => :destroy

  s3_credentials_hash = {
    :access_key_id => ENV['AWS_ACCESS_KEY'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }

  has_attached_file :image, 
                    :styles => { :thumb => "300x225#", :display => "720x540#" },
                    :s3_credentials => s3_credentials_hash,
                    :bucket => ENV['AWS_BUCKET'],
                    :default_url => "https://s3-us-west-2.amazonaws.com/timeauction/missing-auction-thumb.png",
                    :s3_protocol => :https

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  # def to_param
  #   "#{id}-#{title.parameterize}"
  # end

  def donations_per_hour_in_cents
    self.donations.sum(:amount)
  end

  def donations_per_hour
    donations_per_hour_in_cents.to_f / 100
  end

  def num_supporters
    self.donations.select(:user_id).uniq.count
  end

  def unique_supporters
    self.donations.map{|donation| donation.user}.uniq
  end

  def num_hours
    self.journal_entries.sum(:hours)
  end

  def total_donations_raised_in_cents
    donations_per_hour_in_cents * num_hours
  end

  def total_donations_raised_in_dollars
    total_donations_raised_in_cents.to_f / 100
  end

  def social_links_as_string(url)
    str = "<a href='" + ApplicationController.helpers.facebook_link(url, self) + "' target='_blank'><i class='fa fa-facebook-square'></i></a>"
    str += "<a href='" + ApplicationController.helpers.twitter_link(url, self) + "' target='_blank'><i class='fa fa-twitter-square'></i></a>"
    str += "<a href='" + ApplicationController.helpers.linkedin_link(url, self) + "' target='_blank'><i class='fa fa-linkedin-square'></i></a>"
    str += "<a href='" + ApplicationController.helpers.email_link(url, self) + "' target='_blank'><i class='fa fa-envelope-square'></i></a>"
    return str
  end

  def estimated_hours_per_period
    if self.frequency == "monthly"
      multiple = 12 / ApplicationController.helpers.donation_periods_per_year
    elsif self.frequency == "weekly"
      multiple = 52.0 / ApplicationController.helpers.donation_periods_per_year
    end

    if self.estimated_hours.nil? || multiple.nil?
      return 4
    else
      return self.estimated_hours * multiple
    end
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  autocomplete :organization, :name, :full => true
  
  before_filter :authenticate_user!, :only => [:new, :edit]
  before_filter :authorized_user, :only => [:edit, :update, :destroy]

  def index
    @title = "All <span class='highlight'>campaigns</span>"
    @image = "https://s3-us-west-2.amazonaws.com/raisechange/general/generic_shovel.jpg"
    @campaigns = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
    @user = @campaign.user
    @organization = @campaign.organization
    @share_html_as_string = render_to_string(:template => ('layouts/_share_this_buttons.html.slim'), :layout => false, :locals => {:campaign => @campaign} )
  end

  def new
    @campaign = Campaign.new
    @title = "Create <span class='highlight'>campaign</span>"
    @image = "https://s3-us-west-2.amazonaws.com/raisechange/general/generic_shovel.jpg"
    @center = true
  end

  def create
    @campaign = Campaign.new(campaign_params)
    org = Organization.find_by_slug_or_create(params[:campaign][:organization_name])
    @campaign.organization_id = org.id
    if @campaign.save
      flash[:notice] = "\"#{@campaign.title}\" created successfully."
      cookies[:just_created] = true
      redirect_to campaign_path(@campaign)
    else
      flash.now[:alert] = @campaign.errors.full_messages.join(". ") + "."
      render "new"
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
    @organization = @campaign.organization
    @organization.contacts.build unless @organization.contacts.any?
    @title = "Edit <span class='highlight'>campaign</span>"
    @image = "https://s3-us-west-2.amazonaws.com/raisechange/general/generic_shovel.jpg"
    @center = true
  end

  def update
    @campaign = Campaign.find(params[:id])
    @campaign.assign_attributes(campaign_params)
    org = Organization.find_by_slug_or_create(params[:campaign][:organization_name])
    @campaign.organization_id = org.id
    if @campaign.save
      flash[:notice] = "\"#{@campaign.title}\" updated successfully."
      redirect_to campaign_path(@campaign)
    else
      flash.now[:alert] = @campaign.errors.full_messages.join(". ") + "."
      render "edit"
    end
  end

  def destroy
    campaign = Campaign.find(params[:id]).destroy
    flash[:notice] = "\"#{campaign.title}\" has been deleted."
    redirect_to root_path
  end

  private 

  def campaign_params
    params.require(:campaign).permit(
      :id,
      :organization_name,
      :title,
      :description,
      :user_id,
      :organization_id,
      :image,
      :donation_period,
      :estimated_hours,
      :frequency,
      :_destroy
    )
  end

  def authorized_user
    @campaign = Campaign.find(params[:id])
    if !current_user.admin
      if @campaign.user != current_user
        flash[:alert] = "You are not authorized to view this page"
        redirect_to campaign_path(@campaign)
      end
    end
  end
end

app/views/campaigns/_after_creation_modal.html.slim
#after-creation-modal.modal.fade tabindex="-1" role="dialog" ng-controller="AfterCreationModalCtrl"
  .modal-dialog.modal-md
    .modal-content
      .modal-body
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
            | &times;
        .content-holder
          - if current_user && @campaign.user == current_user
            h2
              | Your campaign is ready to rock!
            
            h4.content-suggestion
              = "Woo hoo! Now let's get some supporters."

            h4.content-suggestion
              = "For each person that sponsors you at $1 per hour, you'll raise $#{(@campaign.estimated_hours_per_period * donation_periods_per_year).round} a year (based on your estimated hours)."

          - else
            h2
              = "Help #{@campaign.user.first_name} by sharing!"

            h4.content-suggestion
              | Every dollar of support makes a huge impact.

          h4.content-suggestion
            | So share that love!

          ul.list-inline.social-share-list
            li
              a href="#{facebook_link(request.original_url, @campaign)}" target="_blank"
                .social-share-icon-link
                  i.fa.fa-facebook
            li
              a href="#{twitter_link(request.original_url, @campaign)}" target="_blank"
                .social-share-icon-link
                  i.fa.fa-twitter
            li
              a href="#{linkedin_link(request.original_url, @campaign)}" target="_blank"
                .social-share-icon-link
                  i.fa.fa-linkedin
            li
              a href="#{email_link(request.original_url, @campaign)}" target="_blank"
                .social-share-icon-link
                  i.fa.fa-envelope-o

          .copy-url-section-holder
            h4.content-suggestion
              | You can also copy the below URL to send to your friends and family!
              input.form-control.js-copytextarea value="#{request.original_url.gsub("https://", "")}"

            .btn.btn-primary.js-textareacopybtn
              | Copy URL

            span.copied-text style="display: none;"
              | Copied!

app/views/campaigns/_after_donation_modal.html.slim
#after-donation-modal.modal.fade tabindex="-1" role="dialog" ng-controller="AfterDonationModalCtrl"
  .modal-dialog.modal-md
    .modal-content
      .modal-body
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
            | &times;
        .content-holder
          h2
            = "Thank you for supporting #{@campaign.user.first_name}!"
          
          h5
            | Would you like to write a public message on the campaign page?

          form#add-message action="#{add_donation_message_path}" method="post"
            textarea.add-message class="form-control" rows="3" placeholder="E.g. Go #{@campaign.user.first_name} go!" name="donation[message]"

            br

            .call-to-action-holder
              a.call-to-action ng-click="submitMessage()"
                | Submit
                .arrow-right

          br

          a href="" data-dismiss="modal"
            | No thanks

app/views/campaigns/_campaign_details.html.slim
.campaign-show-details-holder
  h4
    a.campaign-how-it-works href="#" data-toggle="modal" data-target="#how-it-works-modal"
      | How it works
      i.fa.fa-question-circle

    .pull-right.hidden-xs
      = render "campaigns/edit_campaign_text", :campaign => campaign

  .visible-xs-block
    h2
      = campaign.title
      = render "campaigns/edit_campaign_text", :campaign => campaign
    h4
      small
        = "By #{link_to user.full_name, user_path(user)}".html_safe
        .mobile-share-buttons
          = render "layouts/share_this_buttons", :campaign => campaign

    .xs-campaign-stats-holder
      = link_to "Support", new_donation_path(campaign), :class => "button support-button"
      .xs-stats
        div
          = "<strong>#{number_to_currency(campaign.donations_per_hour)}</strong> raised per hour".html_safe
        div
          = "<strong>#{number_with_delimiter(campaign.num_supporters, :delimiter => ",")}</strong> #{'supporter'.pluralize(campaign.num_supporters)}".html_safe
        / div
        /   = "<strong>#{number_with_delimiter(campaign.num_hours, :delimiter => ",")}</strong> #{'hour'.pluralize(campaign.num_hours)} volunteered".html_safe

.campaign-show-statistics.bg-warning.hidden-xs
  .top-title-row
    .row
      .col-xs-12
        .campaign-title
          = campaign.title

  .bottom-stats-row
    .row
      .col-xs-2
        .campaign-show-detailed-stats
          h1
            = number_with_delimiter(campaign.num_supporters, :delimiter => ",")
          p
            = "supporter".pluralize(campaign.num_supporters)

      .col-xs-4
        .campaign-show-detailed-stats
          h1
            = number_to_currency(campaign.donations_per_hour)
          p
            | raised per hour

      .col-xs-3
        .campaign-show-detailed-support-button-holder
          = link_to "Support", new_donation_path(@campaign), :class => "button support-button"

      .col-xs-3
        .campaign-show-share-holder
          a.share-link data-toggle="modal" data-target="#after-creation-modal"
            i.fa.fa-share-alt-square.share-icon
            | Share
          / a.share-link data-toggle="popover" data-placement="bottom" title="Spread the love" data-content="<div class='popover-social-links'>#{@campaign.social_links_as_string(request.original_url)}</div>" data-html="true"

      /   .campaign-show-detailed-stats
      /     h1
      /       = number_with_delimiter(campaign.num_hours, :delimiter => ",")
      /     p
      /       = "#{'hour'.pluralize(campaign.num_hours)} volunteered"

app/views/campaigns/_edit_campaign_text.html.slim
- if user_signed_in? && campaign.user == current_user
  small.edit-campaign
    a href="#{edit_campaign_path(campaign)}"
      i.fa.fa-pencil-square-o
      | Edit

app/views/campaigns/_form.html.slim
.campaign-form-holder ng-controller="CampaignFormCtrl" data-estimated-hours="#{@campaign.estimated_hours}"
  = simple_form_for @campaign, html: { class: 'campaign-form' } do |campaign|
    br
    h4
      | Which organization are you supporting?
    br

    .general-form-holder
      .autocomplete-field-holder
        = campaign.input :organization_name, :as => :autocomplete, :url => autocomplete_organization_name_campaigns_path, :class => "string required form-control organization-name-autocomplete", :append_to => ".autocomplete-field-holder", :placeholder => "E.g. Foodbank", :label => "Name of organization", input_html: { "data-append-to" => ".autocomplete-field-holder" }

    br
    h4
      | Page setup
    br

    .general-form-holder
      = campaign.input :title, :placeholder => "E.g. Let's make sure nobody goes hungry", :label => "Campaign title"

      .campaign-preview-image
        = image_tag @campaign.image.url(:display), :width => "100%" if @campaign.id && @campaign.image.exists?
      .btn.btn-primary.btn-file
        - if @campaign.id
          | Change campaign image
        - else
          | Select campaign image
        = campaign.input :image, label: false, :required => false, input_html: { :accept => "image/jpg, image/jpeg, image/png, image/gif", :class => "string required form-control" }

      .selected-image-file-name
    

      br
      = campaign.input :description, :label => "Why people should support your campaign", input_html: { style: "height: 100px;" }, :as => :text

    br
    h4
      | Estimated volunteering
    br

    .general-form-holder
      p
        | This is just to give your supporters an idea of how much they might be donating in total - it can be a rough estimate.

      .row
        .col-xs-12.col-sm-4
          .form-inline.custom-hours-holder
            .form-group
              label for="customHours"
                | * Estimated Hours 
                i.fa.fa-question-circle.estimated-hours-info-tooltip data-toggle="tooltip" data-placement="top" title="This gives your donors a sense of how much they might have to donate"
              div
                .input-group
                  .input-group-addon ng-click="subtractHour()"
                    i.fa.fa-minus
                  input.custom-hours-input class="form-control" id="estimatedHours" ng-model="hours" type="tel" name="campaign[estimated_hours]"
                  .input-group-addon ng-click="addHour()"
                    i.fa.fa-plus

        .col-xs-12.col-sm-8
          div
            label for="customHours"
              | * Frequency
          div
            .btn-group data-toggle="buttons"
              label.btn.btn-primary class="#{'active' if @campaign.frequency == 'weekly' || @campaign.frequency.nil?}"
                input type="radio" name="campaign[frequency]" id="option1" autocomplete="off" checked="#{'checked' if @campaign.frequency == 'weekly' || @campaign.frequency.nil?}" value="weekly"
                  | Weekly

              label.btn.btn-primary class="#{'active' if @campaign.frequency == 'monthly'}"
                input type="radio" name="campaign[frequency]" id="option2" autocomplete="off" checked="#{'checked' if @campaign.frequency == 'monthly'}" value="monthly"
                  | Monthly

      = campaign.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
      / = campaign.input :donation_period, :as => :hidden, :input_html => { :value => donation_period }

    br
    h4
      | Notes
    br

    .general-form-holder
      p
        = "If you haven't already, please make sure you have read the #{link_to 'FAQ', faq_path, :target => '_blank'}. We want to point out that campaigns are free, and we only take 5% of any funds raised, plus applicable credit card processing fees. This is so that we can continue to offer our unique platform to raise change per volunteer hour.".html_safe
      p
        | Thank you for being a great volunteer, and good luck with the campaign!

    br
    - button_text = @campaign.id ? "Update campaign" : "Create campaign"
    = campaign.button :submit, button_text, :class => "submit-button"

    - if @campaign.id
      div style="margin-top: 10px;"
        = link_to "Delete", { :id => @campaign.id, :action => :destroy }, :method => :delete, data: { confirm: "Are you sure?  You're about to delete this campaign..." }

app/views/campaigns/_grid.html.slim
- organization = campaign.organization
- user = campaign.user
.campaign-main-grid ng-controller="CampaignGridCtrl"
  .row
    .col-xs-12
      h4
        = link_to campaign.title, campaign_path(campaign)
        = render "campaigns/edit_campaign_text", :campaign => campaign
    .col-xs-12
      .grid-section
        = link_to image_tag(campaign.image.url(:thumb), :width => "100%"), campaign_path(campaign) if campaign.image.exists?
      .grid-section.support-detail
        = "#{campaign.num_supporters} #{'person'.pluralize(campaign.num_supporters)} supporting #{organization.name}".html_safe
      ul.list-inline.avatar-list
        - campaign.donations.each do |donation|
          li data-toggle="popover" data-placement="bottom" title="<a href=#{'"' + user_path(donation.user) + '"'}>#{donation.user.full_name}</a>" data-content="<div class='popover-donation-details'>#{donation.details_for_popover_as_string(campaign.user == current_user, donation_period_name)}</div>" data-html="true"
            = avatar(donation.user)

app/views/campaigns/_list.html.slim
- user = campaign.user

.campaign-main-list
  .row
    .col-xs-12.col-sm-6
      .campaign-main-title
        h3
          = link_to campaign.title, campaign_path(campaign)
          = render "campaigns/edit_campaign_text", :campaign => campaign

      .visible-xs-block
        .row
          .col-xs-12
            = link_to image_tag(campaign.image.url(:display), :width => "100%"), campaign_path(campaign), :class => "list-image" if campaign.image.exists?

      .campaign-main-description
        p
          = link_to simple_format(truncate(campaign.description.html_safe, :length => 400, omission: '... (read more)')), campaign_path(campaign)
      .campaign-user-holder
        - if user
          .pull-left.user-image
            = link_to profile_picture(user), user_path(user)
          .pull-left.user-name
            = link_to user.full_name, user_path(user)

      - if current_user && user != current_user
        .clearfix
        .campaign-list-follow-section
          = render "users/follow_section", :location => "campaign_list", :user => user

    .col-sm-6.hidden-xs
      = link_to image_tag(campaign.image.url(:display), :width => "100%"), campaign_path(campaign), :class => "list-image" if campaign.image.exists?

app/views/campaigns/_main_grid.html.slim
- organization = campaign.organization
- user = campaign.user
.campaign-main-grid
  .organization-name
    i.fa.fa-heart
    = "  #{organization.name}"

  .row
    .col-xs-9
      .campaign-main-title
        h3
          = link_to campaign.title, campaign_path(campaign)
          = render "campaigns/edit_campaign_text", :campaign => campaign
      .campaign-main-description
        p
          = link_to truncate(campaign.description, :length => 140), campaign_path(campaign)
      .campaign-user-holder
        - if user
          span
            = link_to avatar(user), user_path(user)
          span.user-name
            = link_to user.full_name, user_path(user)
    .col-xs-3
      = link_to image_tag(campaign.image.url(:display), :width => "100%"), campaign_path(campaign)

app/views/campaigns/_sub_nav_holder.html.slim
.campaign-show-sub-nav-holder
  div role="tabpanel"
    ul class="nav nav-tabs nav-justified" role="tablist"
      li.active role="presentation"
        a href="#description" aria-controls="description" role="tab" data-toggle="tab"
          | Description
      li role="presentation"
        a href="#activities" aria-controls="activities" role="tab" data-toggle="tab"
          | Activity
          span
            = " (#{number_with_delimiter(campaign.journal_entries.count, :delimiter => ',')})"
      li role="presentation"
        a href="#supporters" aria-controls="supporters" role="tab" data-toggle="tab"
          | Support
          span
            = " (#{number_with_delimiter(campaign.donations.count, :delimiter => ',')})"

    .tab-content
      .description-holder role="tabpanel" class="tab-pane active" id="description"
        = Rinku.auto_link(simple_format(campaign.description)).html_safe

      .journal-entries-holder role="tabpanel" class="tab-pane" id="activities"
        - if campaign.journal_entries.any?
          - campaign.journal_entries.order('created_at DESC').each do |je|
            = render "journal_entries/journal_entry_grid", :je => je, :show_campaign_title => false
        - else
          = "#{user.first_name} has not logged any activities yet - stay tuned!".html_safe
            
      .campaign-donations-holder role="tabpanel" class="tab-pane" id="supporters"
        - if campaign.donations.any?
          - campaign.donations.order('created_at DESC').each do |donation|
            = render "donations/donation_grid", :donation => donation
        - else
          = "This campaign has no supporters yet - #{link_to 'be the first', new_donation_path(campaign)}! #{'Did you know you can support your own campaign as well? In fact, we recommend it so that others will see you have some skin in the game too!' if current_user && campaign.user == current_user}".html_safe

app/views/campaigns/edit.html.slim
.row
  .col-xs-12.col-md-6.col-md-offset-3
    = render "campaigns/form"

app/views/campaigns/index.html.slim
.row
  .col-xs-12
    .banner-sub-title
      | All these awesome people are volunteering for great causes - support them with your change!

.main-campaign-list-holder
  - @campaigns.each do |campaign|
    = render "campaigns/list", :campaign => campaign

app/views/campaigns/new.html.slim
.row
  .col-xs-12.col-md-6.col-md-offset-3
    = render "campaigns/form"

app/views/campaigns/show.html.slim
= render "after_creation_modal"
= render "after_donation_modal"
- generate_meta_tags(@campaign.title, @campaign.description, @campaign.image.url(:display))
.row
  .col-xs-12.col-md-8.col-md-offset-2
    .show-campaign-holder ng-controller="CampaignShowCtrl"
      .row
        .col-sm-3.hidden-xs.large-left-column
          .organizer-title
            | AWESOME VOLUNTEER

          = render "users/big_user_picture_and_name", :user => @user

          / = render "layouts/share_this_buttons", :campaign => @campaign

          - if current_user && @user != current_user
            .action-buttons
              = render "users/follow_section", :location => "campaign_page", :user => @user

        .col-xs-12.col-sm-9.large-right-column
          = render "campaign_details", :campaign => @campaign, :user => @user

          = image_tag @campaign.image.url(:display), :width => "100%" if @campaign.image.exists?

          = render "sub_nav_holder", :campaign => @campaign, :user => @user

          h4
            - if @organization.website.blank?
              = "All proceeds go towards: #{link_to @organization.name, 'https://www.google.ca/search?q=' + @organization.name, :target => '_blank'}".html_safe
            - else
              = "All proceeds go towards: #{link_to @organization.name, @organization.website, :target => '_blank'}".html_safe

          .bottom-buttons
            = link_to "Support", new_donation_path(@campaign), :class => "button support-button"

          div
            a href="#{campaigns_path}"
              i.fa.fa-chevron-circle-left
              span.back-to-all-campaigns
                | Back to all campaigns