config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  scope "/admin" do
    post "add-org-admin" => "admins#add_org_admin", as: :add_org_admin
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" }

  root "pages#landing"
  
  get "how-it-works" => "pages#how_it_works", as: :how_it_works
  get "about" => "pages#about", as: :about
  get "faq" => "pages#faq", as: :faq
  get "terms" => "pages#terms", as: :terms
  get "privacy" => "pages#privacy", as: :privacy

  get "create-campaign" => "campaigns#new", as: :new_campaign
  get "edit-campaign/:id" => "campaigns#edit", as: :edit_campaign
  resources :campaigns do
    get :autocomplete_organization_name, :on => :collection
  end
  resources :campaigns, :only => [:index, :show, :create, :update, :destroy]

  get ":campaign_id/donate" => "donations#new", as: :new_donation
  resources :donations, :only => [:create, :destroy]
  post "/donations/add-donation-message" => "donations#add_donation_message", as: :add_donation_message

  resources :journal_entries, :except => [:index, :show]

  post "create-or-update-credit-card" => "users#create_or_update_credit_card", as: :create_or_update_credit_card
  delete "delete-credit-card" => "users#delete_credit_card", as: :delete_credit_card
  resources :users, :only => [:show]

  post "follow/:user_id" => "users#follow", as: :follow
  delete "follow/:user_id" => "users#unfollow", as: :unfollow

  get "charity-admin" => "admins#index", as: :charity_admin
  post "admin/verify/:journal_entry_id" => "admins#verify", as: :verify_journal_entry
  post "admin/verify-all/:org_id" => "admins#verify_all", as: :verify_all_journal_entries_for_org
end

app/views/layouts/_alerts.html.slim
- if notice
  p.notice.alert.alert-success.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true"
        | &times;
    = notice

- if alert
  p.alert.alert-danger.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true"
        | &times;
    = alert

app/views/layouts/_banner_title.html.slim
.banner-title style="background-image:url(#{@image.html_safe})"
  .overlay
  .container.banner-container
    .row
      - if @center
        .col-xs-12.col-md-6.col-md-offset-3
          .title
            = @title.html_safe
      - else
        .col-xs-12
          .title
            .hidden-xs
              .pull-left.profile-picture
                = profile_picture(@user) if @user_profile_image
              - if !@own_page && @user_profile_image && user_signed_in?
                .pull-left.title-text.follow-section-title
                  = @title.html_safe
                  .clearfix
                  = render "users/follow_section", :location => "banner", :user => @user
              - else
                .pull-left.title-text
                  = @title.html_safe

            .visible-xs-block
              div.title-text
                = @title.html_safe
              .pull-left.profile-picture
                = profile_picture(@user) if @user_profile_image
              - if !@own_page && @user_profile_image && user_signed_in?
                .mobile-follow-section-holder
                  = render "users/follow_section", :location => "banner", :user => @user

app/views/layouts/_facebook.html.erb
<div id="fb-root"></div>
<% if Rails.env.development? %>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '952931041384040',
        xfbml      : true,
        version    : 'v2.2'
      });
    };
  </script>
<% else %>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '952917808052030',
        xfbml      : true,
        version    : 'v2.2'
      });
    };
  </script>
<% end %>
<script>
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_footer.html.slim
- footer_links = link_to "FAQ", faq_path
- footer_links += " ⋅ "
- footer_links += link_to "About", about_path
- footer_links += " ⋅ "
- footer_links += link_to "Terms", terms_path
- footer_links += " ⋅ "
- footer_links += link_to "Privacy", privacy_path

footer.footer
  .hidden-xs
    .pull-left.raise-change-links
      = image_tag "https://s3-us-west-2.amazonaws.com/raisechange/general/Raise_Change_token.png", :width => "50"
      = footer_links.html_safe
    .pull-right
      = render "layouts/footer_social_links"

  .visible-xs-block
    .raise-change-links
      = footer_links.html_safe
    .mobile-social-links
      = render "layouts/footer_social_links"

app/views/layouts/_footer_social_links.html.slim
ul.list-inline
  li
    a href="https://www.facebook.com/goraisechange" target="_blank"
      .footer-icon-link
        i.fa.fa-facebook
  li
    a href="https://twitter.com/raisechange" target="_blank"
      .footer-icon-link
        i.fa.fa-twitter
  li
    a href="https://instagram.com/raisechange" target="_blank"
      .footer-icon-link
        i.fa.fa-instagram
  li
    a href="mailto:#{general_contact_email}" target="_blank"
      .footer-icon-link
        i.fa.fa-envelope-o

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-4320795-13', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_not_ie.html.slim
#not-ie
  h1
    | Welcome to Raise Change...
  h4
    | ...as viewed on Internet Explorer 8 or below.
  br
  br
  h3
    = "Raise Change works best on modern browsers such as #{link_to 'Chrome', 'http://www.google.com/chrome/'}, #{link_to 'Firefox', 'https://www.mozilla.org/en-US/firefox/new/'}, or #{link_to 'Internet Explorer 9', 'http://windows.microsoft.com/en-US/internet-explorer/download-ie'} and above.".html_safe
  h3
    | Look forward to seeing you there :)

app/views/layouts/_share_this_buttons.html.slim
.share-this-buttons
  - facebook_app_id = Rails.env.development? ? 952931041384040 : 952917808052030
  - facebook_link = "https://www.facebook.com/dialog/feed"
  - facebook_link += "?app_id=#{facebook_app_id}"
  - facebook_link += "&display=popup"
  - facebook_link += "&caption=Raise%20Change"
  - facebook_link += "&link=#{request.original_url}"
  - facebook_link += "&redirect_uri=#{request.original_url}"
  - facebook_link += "&picture=#{campaign.image.url(:display)}"

  - twitter_link = "https://twitter.com/intent/tweet"
  - twitter_link += "?text=#{campaign.title}"
  - twitter_link += "&url=#{request.original_url}"
  - twitter_link += "&hashtags=raisechange"

  - linkedin_link = "https://www.linkedin.com/shareArticle"
  - linkedin_link += "?mini=true"
  - linkedin_link += "&url=#{request.original_url}"
  - linkedin_link += "&title=#{campaign.title}"

  a href="#{facebook_link}" target="_blank"
    i.fa.fa-facebook-square

  a href="#{twitter_link}" target="_blank"
    i.fa.fa-twitter-square

  a href="#{linkedin_link}" target="_blank"
    i.fa.fa-linkedin-square
  
  

app/views/layouts/_share_this_js.html.erb
<head>
  <script type="text/javascript">var switchTo5x=true;</script>
  <script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript">stLight.options({publisher: "b5140d3f-2411-4c8b-b53e-c1312f6f1bd1", doNotHash: true, doNotCopy: false, hashAddressBar: true});</script>
</head>

app/views/layouts/_stripe_javascript.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<% if Rails.env.production? %>
  <script type="text/javascript">
    Stripe.setPublishableKey('pk_live_0UuzXEDTjecVaa3BS3b7c9IF');
  </script>
<% else %>
  <script type="text/javascript">
    Stripe.setPublishableKey('pk_test_1axbOa1BUUhimyEaAzXTykbK');
  </script>
<% end %>

app/views/layouts/_top_nav.html.slim
nav.navbar.navbar-default role="navigation"
  .navbar-header
    button.navbar-toggle.collapsed data-target="#navbar-collapse-1" data-toggle="collapse" type="button" 
      span.sr-only
        | Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar

    a.brand-logo href="#{root_path}"
      .visible-xs-block
        = image_tag "https://s3-us-west-2.amazonaws.com/raisechange/general/Raise_Change_logo_2_tight.png", :width => 100, :style => "margin-bottom: 5px;"
      .hidden-xs
        = image_tag "https://s3-us-west-2.amazonaws.com/raisechange/general/Raise_Change_logo_2_tight.png", :width => 200
      
  #navbar-collapse-1.collapse.navbar-collapse
    ul.nav.navbar-nav.navbar-right
      li
        = switch_user_select
      li
        a href="" data-toggle="modal" data-target="#how-it-works-modal"
          | How it works

      li
        a href="#{campaigns_path}" class="#{'active-underline' if params[:action] == 'index' && params[:controller] == 'campaigns'}"
          | Browse

      / li
      /   a href="#{about_path}" class="#{'active-underline' if params[:action] == 'about' && params[:controller] == 'pages'}"
      /     | About

      - if user_signed_in?
        li
          - if can_create_journal_entries?
            a href="#{new_journal_entry_path}" style="margin-right: 10px;" class="#{'active-underline' if params[:action] == 'new' && params[:controller] == 'journal_entries'}"
              | Log hours
          - else
            a href="#{new_campaign_path}" style="margin-right: 10px;" class="#{'active-underline' if params[:action] == 'new' && params[:controller] == 'campaigns'}"
              | Create campaign

        li.navbar-avatar
          = avatar(current_user)

        li.dropdown
          a.dropdown-toggle.user-account-dropdown href="#" data-toggle="dropdown" role="button" aria-expanded="false"
            = current_user.first_name
            span.caret
          ul.dropdown-menu
            li
              a href="#{root_path}" class="#{'highlighted-dropdown' if params[:action] == 'landing' && params[:controller] == 'pages'}"
                | News feed

            - if can_create_journal_entries?
              li
                a href="#{new_campaign_path}" class="#{'highlighted-dropdown' if params[:action] == 'new' && params[:controller] == 'campaigns'}"
                  | Create campaign

            li
              a href="#{user_path(current_user)}" class="#{'highlighted-dropdown' if params[:action] == 'show' && params[:controller] == 'users' && @user == current_user}"
                | Profile page

            li.divider

            - if current_user.organizations_as_admin.any?
              li
                a href="#{charity_admin_path}" class="#{'highlighted-dropdown' if params[:action] == 'index' && params[:controller] == 'admins'}"
                  | Charity admin

            li
              a href="#{edit_user_registration_path}" class="#{'highlighted-dropdown' if params[:action] == 'edit' && params[:controller] == 'registrations'}"
                | Account settings
                
            li
              = link_to "Logout", destroy_user_session_path, :method => :delete

      - else
        li
          a href="#{new_user_registration_path}" class="#{'active-underline' if params[:action] == 'new' && params[:controller] == 'registrations'}"
            | Sign up free
        li
          a href="#{new_user_session_path}" class="#{'active-underline' if params[:action] == 'new' && params[:controller] == 'sessions'}"
            | Login

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="raisechange">
  <!--[if IE 9]>
    <html class="lt-ie10" lang="en">
  <![endif]-->
  <!--[if lt IE 9]>
    <style>#wrap{display:none;}#not-ie{display:block!important;}</style>
  <![endif]-->
  <head>
    <% 
      title = "Raise Change ⋅ Micro donations for each hour you volunteer"
      description = "Raise Change is a platform that allows you to crowdsource micro donations for each volunteer hour that you do."
    %>

    <% meta :title => title, :description => description, :keywords => %w(raise change volunteer hour micro donations crowdsource) %>

    <% facebook_app_id = Rails.env.development? ? 952931041384040 : 952917808052030 %>

    <% 
      meta [:property => "og:url", :content => "https://www.raisechange.com"]
      meta [:property => "og:title", :content => title]
      meta [:property => "og:description", :content => description]
      meta [:property => "og:image", :content => "https://s3-us-west-2.amazonaws.com/raisechange/general/victory.jpg"]
      meta [:property => "og:type", :content => "website"]
      meta [:property => "fb:admins", :content => "81007543"]
      meta [:property => "fb:app_id", :content => facebook_app_id]
    %>

    <%= metamagic %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= render "layouts/stripe_javascript" %>
    <%= render "layouts/google_analytics" if Rails.env.production? %>
    <meta name="google-site-verification" content="4W06qW6z6ZADdxJU_-o6SqQKAvO7YSHtUm66W_cV7ew" />
  </head>
  <body>
    <div id="wrap">
      <%= render "layouts/facebook" %>
      <%= render "layouts/top_nav" %>
      <%= render "layouts/banner_title" if @title && @image %>
      <%= render "layouts/alerts" %>
      <%= render "pages/how_it_works_modal" %>
      <% unless params[:action] == 'landing' && params[:controller] == 'pages' %>
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="main-content">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
      <%= render "layouts/footer" %>
    </div>
    <%= render "layouts/not_ie" %>
  </body>
</html>